# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: HTB Progress

# Controls when the workflow will run
on:
  # Triggers the workflow to run every day at 00:00
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        #with:
        #  token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Firefox
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo systemctl enable snapd
          sudo systemctl start snapd
          sudo snap install firefox
      - name: Fetches the new HTB Data, and updates the readme
        run: |
          cd $GITHUB_WORKSPACE && python3 fetch_htb_data.py
      - name: Pushes the changes
        run: |
          git config --global user.name 'Scrayil'
          git config --global user.email 'mattia.bennati@mailbox.org'
          git commit -am "Automated HTB progress fetch"
          git push
